
OAUTH_TOKEN:
OAUTH_SECRET:
CONSUMER_KEY:
CONSUMER_SECRET:
TWITTER_HANDLE:
FOLLOWERS_FILE:followers.txt
FOLLOWS_FILE:following.txt
USERS_FOLLOWING:
USERS_UNMUTED:
USERS_MUTED:
FOLLOW_REFRESH_SECONDS:10
